---
title: "NISS Submission"
author: "Yichi Zhang and Winnie Wing-Yee Tse"
Institution : "University of Southern California"
date: '2022-04-18'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## URL to R shiny

Here is the link to our Rshiny web application: https://uncover-data-stories.shinyapps.io/NAEP-Reading-Scores/

## Educational Interest and Interpretation

The data set we used examines the average National Assessment of Educational Progress (NAEP) reading scale score of 8th grade students in public schools in the United States. It includes the nationally representative assessment results from 1998 to 2019. Our Interactive R shiny application displays the average reading scale scores and associated confidence intervals by states, and visually depicts the trend of reading scores in the last two decades. Our app allows users to make direct comparisons of interested states and trace students' performance on the NAEP reading scale over time. 


## Accessibility Statement

The Shiny application can be viewed across web browsers and electronic devices, including mobile phones, tablets, and computers. We provide instructions for using the application in the front page, along with our contact methods for inquiries. Despite our efforts to make the application as accessible as possible, it has two limitations. First, the content is written English and is exclusive to English-readers. Second, images in the applications do not come with text descriptions, and we supplement a table that summarizes the reading scores and standard errors for the selected State(s) and year(s). 


